{% set name = "pyglotaran" %}
{% set version = "0.7.2" %}
{% set download_name = "pyglotaran" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ download_name[0] }}/{{ download_name }}/{{ download_name }}-{{ version }}.tar.gz
  sha256: aa9f9b10a9d554017e444e6522ec87cfa9ace682ee8e8f98a4660c2424c5c0de

build:
  number: 0
  noarch: python
  entry_points:
    - glotaran=glotaran.cli.main:main
  script: {{ PYTHON }} -m pip install . --no-deps --ignore-installed -vv

requirements:
  host:
    - pip
    - python >=3.10,<3.12
  run:
    - python >=3.10,<3.12
    - asteval !=0.9.28,>=0.9.22
    - attrs >=22.1.0
    - click >=8.1.3
    - netCDF4 >=1.5.7
    - numba >=0.55.0
    - numpy >=1.21.2,<1.25
    - odfpy >=1.4.1
    - openpyxl >=3.0.10
    - pandas >=1.3.4
    - pydantic >=1.10.2
    - rich >=10.9.0
    - ruamel.yaml >=0.17.17
    - scipy >=1.7.2
    - sdtfile >=2020.8.3
    - tabulate >=0.8.9
    - xarray >=2022.3.0

test:
  imports:
    - glotaran
  source_files:
    - glotaran
  commands:
    - glotaran --help
    - pytest glotaran
  requires:
    - pytest
    - ipython

about:
  home: https://github.com/glotaran/pyglotaran
  license: LGPL-3.0-only
  license_family: LGPL
  license_file: LICENSE
  summary: The Glotaran fitting engine.
  doc_url: https://pyglotaran.readthedocs.io/en/latest/?badge=latest
  dev_url: https://github.com/glotaran/pyglotaran

extra:
  recipe-maintainers:
    - s-weigand
    - joernweissenborn
    - jsnel
