{% set name = "pyglotaran" %}
{% set version = "0.5.1" %}
{% set download_name = "pyglotaran" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ download_name[0] }}/{{ download_name }}/{{ download_name }}-{{ version }}.tar.gz
  sha256: 996dee1f2cf205a31d67866f5e6ff60635f6b1f9bc7bec6b016b1b2bfd6a5e2b

build:
  number: 0
  noarch: python
  entry_points:
    - glotaran=glotaran.cli.main:main
  script: {{ PYTHON }} -m pip install . --no-deps --ignore-installed -vv

requirements:
  host:
    - pip
    - python >=3.8,<3.10
  run:
    - python >=3.8,<3.10
    - asteval >=0.9.21
    - click >=7.0
    - netcdf4 >=1.5.3
    - numba >=0.52
    - numpy >=1.20.0,<1.21
    - pandas >=0.25.2
    - rich >=10.9.0
    - ruamel.yaml >=0.17.17
    - scipy >=1.3.2
    - sdtfile >=2020.8.3
    - setuptools >=41.2
    - tabulate >=0.8.8
    - xarray !=0.20.0,!=0.20.1,>=0.16.2

test:
  imports:
    - glotaran
  source_files:
    - glotaran
  commands:
    - glotaran --help
    - pytest glotaran
  requires:
    - pytest
    - ipython

about:
  home: https://github.com/glotaran/pyglotaran
  license: LGPL-3.0-only
  license_family: LGPL
  license_file: LICENSE
  summary: The Glotaran fitting engine.
  doc_url: https://pyglotaran.readthedocs.io/en/latest/?badge=latest
  dev_url: https://github.com/glotaran/pyglotaran

extra:
  recipe-maintainers:
    - s-weigand
    - joernweissenborn
    - jsnel
