{% set python_min = '3.10' %}
{% set name = "pyglotaran" %}
{% set version = "0.7.3" %}
{% set download_name = "pyglotaran" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.org/packages/source/{{ download_name[0] }}/{{ download_name }}/{{ download_name }}-{{ version }}.tar.gz
  sha256: eea5700a58c89b5f0581f875845ba2504facd29bf618fe46196f6e532abfa2f5

build:
  number: 1
  noarch: python
  entry_points:
    - glotaran=glotaran.cli.main:main
  script: {{ PYTHON }} -m pip install . --no-deps --ignore-installed -vv

requirements:
  host:
    - pip
    - setuptools
    - python {{ python_min }}
  run:
    - python >={{ python_min }},<3.12
    - asteval !=0.9.28,>=0.9.22
    - attrs >=22.1.0
    - click >=8.1.3
    - netCDF4 >=1.5.7
    - numba >=0.55.0
    - numpy >=1.21.2,<1.27
    - odfpy >=1.4.1
    - openpyxl >=3.0.10
    - pandas >=1.3.4
    - pydantic >=1.10.2
    - ruamel.yaml >=0.17.17
    - scipy >=1.7.2
    - sdtfile >=2020.8.3
    - tabulate >=0.8.9
    - xarray >=2022.3.0

test:
  imports:
    - glotaran
  source_files:
    - glotaran
  commands:
    - glotaran --help
    - pytest glotaran
  requires:
    - pytest
    - ipython
    - python {{ python_min }}

about:
  home: https://github.com/glotaran/pyglotaran
  license: LGPL-3.0-only
  license_family: LGPL
  license_file: LICENSE
  summary: A Python library for Global and Target Analysis of time-resolved spectroscopy data.
  description: |
    Pyglotaran is a python library for global analysis of time-resolved spectroscopy data. It is designed to provide a state of the art modeling toolbox to researchers, in a user-friendly manner.

    Its features are:
    - user-friendly modeling with a custom YAML (*.yml) based modeling language
    - parameter optimization using variable projection and non-negative least-squares algorithms
    - easy to extend modeling framework
    - battle-hardened model and algorithms for fluorescence dynamics
    - build upon and fully integrated in the standard Python science stack (NumPy, SciPy, Jupyter)

    pyglotaran is ideal for researchers and scientists who require a powerful, yet user-friendly tool for analyzing complex systems, from time-resolved spectroscopy to broader applications in scientific modeling.
  doc_url: https://pyglotaran.readthedocs.io/en/latest/?badge=latest
  dev_url: https://github.com/glotaran/pyglotaran

extra:
  recipe-maintainers:
    - s-weigand
    - joernweissenborn
    - jsnel
