{% set name = "pyglotaran" %}
{% set version = "0.3.2" %}
{% set download_name = "pyglotaran" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ download_name[0] }}/{{ download_name }}/{{ download_name }}-{{ version }}.tar.gz
  sha256: c6d98ef37166c620f083d9bd14714cbb06d2f5c57ae020f297c84c6b9224839b

build:
  number: 0
  noarch: python
  entry_points:
    - glotaran=glotaran.cli.main:glotaran
  script: {{ PYTHON }} -m pip install . --no-deps --ignore-installed -vv

requirements:
  host:
    - pip
    - python >=3.8,<3.9
  run:
    - python >=3.8,<3.9
    - asteval >=0.9.21
    - click >=7.0
    - netcdf4 >=1.5.3
    - numba >=0.48
    - numpy >=1.19.5,<1.20.0
    - pandas >=0.25.2
    - pyyaml >=5.2
    - scipy >=1.3.2
    - sdtfile >=2020.8.3
    - setuptools >=41.2
    - xarray >=0.14

test:
  imports:
    - glotaran
  source_files:
    - glotaran
  commands:
    - glotaran --help
    - pytest -k "not IrfDispersion" glotaran
  requires:
    - pytest

about:
  home: https://github.com/glotaran/pyglotaran
  license: LGPL-3.0-only
  license_family: LGPL
  license_file: LICENSE
  summary: The Glotaran fitting engine.
  doc_url: https://pyglotaran.readthedocs.io/en/latest/?badge=latest
  dev_url: https://github.com/glotaran/pyglotaran

extra:
  recipe-maintainers:
    - s-weigand
    - joernweissenborn
    - jsnel
