{% set name = "pyglotaran" %}
{% set version = "0.2.0" %}
{% set download_name = "pyglotaran" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ download_name[0] }}/{{ download_name }}/{{ download_name }}-{{ version }}.tar.gz
  sha256: 5fea438af84fdd1818133d0d725c889520ca9f34e476083b5d3d9a5672eff414

build:
  number: 0
  noarch: python
  entry_points:
    - glotaran=glotaran.cli.main:glotaran
  script: {{ PYTHON }} -m pip install . --no-deps --ignore-installed -vv

requirements:
  host:
    - pip
    - python >=3.8,<3.9
    - pytest-runner
  run:
    - python >=3.8,<3.9
    - pytest-runner
    - click >=7.0
    - lmfit >=0.9.13,<1.0.1
    - netcdf4 >=1.5.3
    - numba >=0.48
    - numpy >=1.17.3
    - pandas >=0.25.2
    - pyyaml >=5.2
    - scipy >=1.3.2
    - setuptools >=41.2
    - xarray >=0.14

test:
  imports:
    - glotaran
  source_files:
    - glotaran
  commands:
    - glotaran --help
    - pytest -k "not IrfDispersion" glotaran
  requires:
    - pytest

about:
  home: https://github.com/glotaran/pyglotaran
  license: GPL-3.0-only
  license_family: GPL3
  license_file: LICENSE
  summary: The Glotaran fitting engine.
  doc_url: https://pyglotaran.readthedocs.io/en/latest/?badge=latest
  dev_url: https://github.com/glotaran/pyglotaran

extra:
  recipe-maintainers:
    - s-weigand
    - joernweissenborn
    - jsnel
